// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiModulo10.Contexts;

namespace WebApiModulo10.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200811210809_nuevo-autor")]
    partial class nuevoautor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiModulo10.Entities.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaNacimiento = new DateTime(1900, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Felipe Gavilán"
                        },
                        new
                        {
                            Id = 2,
                            FechaNacimiento = new DateTime(1905, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Claudia Rodríguez"
                        },
                        new
                        {
                            Id = 3,
                            FechaNacimiento = new DateTime(1985, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Alejandro Lopera"
                        });
                });

            modelBuilder.Entity("WebApiModulo10.Entities.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Libro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutorId = 1,
                            Titulo = "Entity Framework Core 2.1 - De verdad"
                        },
                        new
                        {
                            Id = 2,
                            AutorId = 2,
                            Titulo = "Construyendo Web APIs con ASP.NET Core 2.2"
                        },
                        new
                        {
                            Id = 3,
                            AutorId = 2,
                            Titulo = "Libro de prueba"
                        });
                });

            modelBuilder.Entity("WebApiModulo10.Entities.Libro", b =>
                {
                    b.HasOne("WebApiModulo10.Entities.Autor", "Autor")
                        .WithMany("Books")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
